"""Initial migration with all 14 tables

Revision ID: b054bbeabdb8
Revises: 
Create Date: 2025-11-03 01:18:35.863247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b054bbeabdb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('INFO', 'EVALUATION', 'OTHER', name='competencycategory'), nullable=False),
    sa.Column('input_type', sa.Enum('TEXT', 'SELECT', 'NUMBER', 'FILE', name='inputtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_competency_items_item_code'), 'competency_items', ['item_code'], unique=True)
    op.create_index(op.f('ix_competency_items_item_id'), 'competency_items', ['item_id'], unique=False)
    op.create_table('data_retention_policy',
    sa.Column('policy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('retention_period_years', sa.Integer(), nullable=False),
    sa.Column('action_on_expiry', sa.Enum('ARCHIVE', 'DELETE', 'ANONYMIZE', name='actiononexpiry'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('data_type')
    )
    op.create_index(op.f('ix_data_retention_policy_policy_id'), 'data_retention_policy', ['policy_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birthdate', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('COACH', 'STAFF', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('coach_certification_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('competency_reminders',
    sa.Column('reminder_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('last_reminder_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_reminder_date', sa.Date(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    op.create_index(op.f('ix_competency_reminders_reminder_id'), 'competency_reminders', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_competency_reminders_user_id'), 'competency_reminders', ['user_id'], unique=True)
    op.create_table('files',
    sa.Column('file_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('upload_purpose', sa.Enum('PROOF', 'PROFILE', 'OTHER', name='uploadpurpose'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_deletion_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_files_file_id'), 'files', ['file_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recruitment_start_date', sa.Date(), nullable=False),
    sa.Column('recruitment_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RECRUITING', 'REVIEWING', 'COMPLETED', 'CLOSED', name='projectstatus'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWING', 'COMPLETED', name='applicationstatus'), nullable=False),
    sa.Column('auto_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_visibility', sa.Enum('ADMIN_ONLY', 'PUBLIC', name='scorevisibility'), nullable=False),
    sa.Column('can_submit', sa.Boolean(), nullable=False),
    sa.Column('selection_result', sa.Enum('PENDING', 'SELECTED', 'REJECTED', name='selectionresult'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_applications_project_id'), 'applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('coach_competencies',
    sa.Column('competency_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUPPLEMENTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['competency_items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('competency_id')
    )
    op.create_index(op.f('ix_coach_competencies_competency_id'), 'coach_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_coach_competencies_user_id'), 'coach_competencies', ['user_id'], unique=False)
    op.create_table('project_items',
    sa.Column('project_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('proof_required', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['competency_items.item_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_item_id')
    )
    op.create_index(op.f('ix_project_items_project_item_id'), 'project_items', ['project_item_id'], unique=False)
    op.create_table('project_staff',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'staff_user_id')
    )
    op.create_table('application_data',
    sa.Column('data_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_value', sa.Text(), nullable=True),
    sa.Column('submitted_file_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='verification_status_enum'), nullable=False),
    sa.Column('item_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competency_id'], ['coach_competencies.competency_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['competency_items.item_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['submitted_file_id'], ['files.file_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_index(op.f('ix_application_data_application_id'), 'application_data', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_data_data_id'), 'application_data', ['data_id'], unique=False)
    op.create_table('review_locks',
    sa.Column('lock_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['competency_items.item_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lock_id'),
    sa.UniqueConstraint('application_id', 'item_id', name='uq_application_item_lock')
    )
    op.create_index(op.f('ix_review_locks_application_id'), 'review_locks', ['application_id'], unique=False)
    op.create_index(op.f('ix_review_locks_lock_id'), 'review_locks', ['lock_id'], unique=False)
    op.create_table('scoring_criteria',
    sa.Column('criteria_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_item_id', sa.Integer(), nullable=False),
    sa.Column('matching_type', sa.Enum('EXACT', 'CONTAINS', 'RANGE', name='matchingtype'), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['project_item_id'], ['project_items.project_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('criteria_id')
    )
    op.create_index(op.f('ix_scoring_criteria_criteria_id'), 'scoring_criteria', ['criteria_id'], unique=False)
    op.create_table('custom_questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('allows_text', sa.Boolean(), nullable=False),
    sa.Column('allows_file', sa.Boolean(), nullable=False),
    sa.Column('file_required', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_custom_questions_question_id'), 'custom_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_custom_questions_project_id'), 'custom_questions', ['project_id'], unique=False)
    op.create_table('custom_question_answers',
    sa.Column('answer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_file_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['answer_file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['custom_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_custom_question_answers_answer_id'), 'custom_question_answers', ['answer_id'], unique=False)
    op.create_index(op.f('ix_custom_question_answers_application_id'), 'custom_question_answers', ['application_id'], unique=False)
    op.create_index(op.f('ix_custom_question_answers_question_id'), 'custom_question_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_question_answers_question_id'), table_name='custom_question_answers')
    op.drop_index(op.f('ix_custom_question_answers_application_id'), table_name='custom_question_answers')
    op.drop_index(op.f('ix_custom_question_answers_answer_id'), table_name='custom_question_answers')
    op.drop_table('custom_question_answers')
    op.drop_index(op.f('ix_custom_questions_project_id'), table_name='custom_questions')
    op.drop_index(op.f('ix_custom_questions_question_id'), table_name='custom_questions')
    op.drop_table('custom_questions')
    op.drop_index(op.f('ix_scoring_criteria_criteria_id'), table_name='scoring_criteria')
    op.drop_table('scoring_criteria')
    op.drop_index(op.f('ix_review_locks_lock_id'), table_name='review_locks')
    op.drop_index(op.f('ix_review_locks_application_id'), table_name='review_locks')
    op.drop_table('review_locks')
    op.drop_index(op.f('ix_application_data_data_id'), table_name='application_data')
    op.drop_index(op.f('ix_application_data_application_id'), table_name='application_data')
    op.drop_table('application_data')
    op.drop_table('project_staff')
    op.drop_index(op.f('ix_project_items_project_item_id'), table_name='project_items')
    op.drop_table('project_items')
    op.drop_index(op.f('ix_coach_competencies_user_id'), table_name='coach_competencies')
    op.drop_index(op.f('ix_coach_competencies_competency_id'), table_name='coach_competencies')
    op.drop_table('coach_competencies')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_project_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_files_file_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_competency_reminders_user_id'), table_name='competency_reminders')
    op.drop_index(op.f('ix_competency_reminders_reminder_id'), table_name='competency_reminders')
    op.drop_table('competency_reminders')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_data_retention_policy_policy_id'), table_name='data_retention_policy')
    op.drop_table('data_retention_policy')
    op.drop_index(op.f('ix_competency_items_item_id'), table_name='competency_items')
    op.drop_index(op.f('ix_competency_items_item_code'), table_name='competency_items')
    op.drop_table('competency_items')
    # ### end Alembic commands ###
