"""Add coaching fields and coach profile

Revision ID: dd566951a79d
Revises: b054bbeabdb8
Create Date: 2025-11-03 02:21:03.288607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd566951a79d'
down_revision = 'b054bbeabdb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coaching_fields', sa.String(length=500), nullable=True))
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('users', 'coaching_fields')
    # ### end Alembic commands ###
