"""Change role to roles array

Revision ID: 158e7b2bc2e2
Revises: dd566951a79d
Create Date: 2025-11-03 02:53:32.076263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '158e7b2bc2e2'
down_revision = 'dd566951a79d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.String(length=200), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('COACH', 'STAFF', 'ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
